import { Card, Btn } from "../ui/UI";

export default function PreviewGate({ GROQ_API_KEY, enterPreview }) {
  return (
    <div>
      <Card style={{ border: "1px solid #1e3a1e" }}>
        <div style={{ fontSize: 13, fontWeight: 600, color: "#4ade80", marginBottom: 8 }}>✅ All set!</div>
        <div style={{ fontSize: 12.5, color: "#7a90a8", lineHeight: 1.6 }}>
          Clicking below will open the full A4 preview.
          {GROQ_API_KEY !== "YOUR_GROQ_API_KEY_HERE"
            ? " Your Professional Summary will be auto-generated by Groq AI."
            : " Add your API key to the top of the file to enable AI summary generation."}
        </div>
      </Card>
      <Btn full onClick={enterPreview}>🚀 Generate &amp; Preview Resume →</Btn>
    </div>
  );
}
